stages:
  - build
  - deploy

build_project:
  stage: build
  image: node:20
  variables:
    VITE_MAPBOX_TOKEN: "${VITE_MAPBOX_TOKEN}"
  script:
    - |
      if [ -z "$VITE_MAPBOX_TOKEN" ]; then
        echo "Warning: VITE_MAPBOX_TOKEN is not set"
      else
        echo "VITE_MAPBOX_TOKEN is set (length: ${#VITE_MAPBOX_TOKEN})"
      fi
    - npm install
    - npm run build

deploy_project:
  stage: deploy
  image: node:20
  variables:
    VITE_MAPBOX_TOKEN: "${VITE_MAPBOX_TOKEN}"
  script:
    - |
      HTTP_STATUS=$(curl -s -o response.txt -w "%{http_code}" -X POST "https://ikgcartoapps.ethz.ch/deploy/project" \
      -H "Content-Type: application/json" \
      -H "x-project-secret: ${CI_PROJECT_SECRET}" \
      -H "x-env-VITE_MAPBOX_TOKEN: ${VITE_MAPBOX_TOKEN}" \
      -d "{\"repository\": \"${CI_PROJECT_NAME}\", \"namespace\": \"${CI_PROJECT_NAMESPACE}\", \"environmentVariables\": {\"VITE_MAPBOX_TOKEN\": \"${VITE_MAPBOX_TOKEN}\"}}")
      
      if [ -f response.txt ]; then
        cat response.txt
      else
        echo "No response received."
      fi

      if [ "$HTTP_STATUS" -ne 200 ]; then
        exit 1
      fi
  only:
    - main
  when: manual
  allow_failure: false